CREATE TABLE general(
    id_general INT PRIMARY KEY AUTO_INCREMENT,
    id_solicitante INT,
    id_empresa INT,
    titulo VARCHAR(100),
    intereses VARCHAR(500),
    habilidades VARCHAR(500),
    id_grado_estudio INT,
    id_experiencia INT,
    id_modalidad INT,
    id_edad INT,
    id_jornada_laboral INT,
    id_salario INT,
    prestaciones VARCHAR(500),
    id_idioma INT,
    id_contrato INT,
    FOREIGN KEY(id_solicitante) REFERENCES solicitantes(id_solicitante),
    FOREIGN KEY(id_empresa) REFERENCES empresas(id_empresa),
    FOREIGN KEY(id_grado_estudio) REFERENCES grado_estudios(id_grado_estudio),
    FOREIGN KEY(id_experiencia) REFERENCES experiencias(id_experiencia),
    FOREIGN KEY(id_modalidad) REFERENCES modalidades(id_modalidad),
    FOREIGN KEY(id_edad) REFERENCES edades(id_edad),
    FOREIGN KEY(id_jornada_laboral) REFERENCES jornadas_laborales(id_jornada_laboral),
    FOREIGN KEY(id_salario) REFERENCES salarios(id_salario),
    FOREIGN KEY(id_idioma) REFERENCES idiomas(id_idioma),
    FOREIGN KEY(id_contrato) REFERENCES contratos(id_contrato),
);